#!/usr/bin/env bash


feh --bg-max "$(cat ~/.wallpaperc)"
polybar

bspc config border_width  2
bspc config window_gap    2

bspc config focus_follows_pointer  true
bspc config pointer_follows_focus  true 

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config top_padding    25
bspc config bottom_padding 1
bspc config left_padding   1
bspc config right_padding  1
