#!/usr/bin/env bash


feh --bg-scale "$(cat ~/.wallpaperc)" 

bspc config border_width  5
bspc config window_gap    5

bspc config focus_follows_pointer  true
bspc config pointer_follows_focus  true 

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config top_padding    21
bspc config bottom_padding 0
bspc config left_padding   0
bspc config right_padding  0
